services:
  keycast-api:
    container_name: keycast-api
    build: .
    command: api
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "api"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - keycast
    labels:
      - "caddy=${DOMAIN:?error}"
      - "caddy.reverse_proxy=/api/* {{upstreams 3000}}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

  keycast-web:
    container_name: keycast-web
    build:
      context: .
      args:
        - VITE_DOMAIN=${DOMAIN:?error}
        - VITE_ALLOWED_PUBKEYS=${ALLOWED_PUBKEYS}
    command: web
    expose:
      - "5173"
    depends_on:
      keycast-api:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - WAIT_FOR_API=true
      - HOST=0.0.0.0
      - PORT=5173
      - "VITE_DOMAIN=${DOMAIN:?error}"
      - "VITE_ALLOWED_PUBKEYS=${ALLOWED_PUBKEYS}"
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "web"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - keycast
    labels:
      - "caddy=${DOMAIN:?error}"
      - "caddy.reverse_proxy=/* {{upstreams 5173}}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

networks:
  keycast:
    external: true
    name: keycast
