[package]
name = "keycast-generate-master-key"
description = "Generate a master key for the keycast application"
authors = ["Keycast Authors"]
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = { workspace = true }
rand = { workspace = true }
