[package]
name = "keycast"
description = "A Nostr key manager and remote signer"
author = "Keycast Authors"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10"
async-trait = "0.1"
axum = "0.7"
base64 = "0.22"
chrono = {version = "0.4", features = ["serde"]}
clap = {version = "4.5", features = ["derive"]}
dotenv = "0.15"
nostr-sdk = {version = "0.37", features = ["nip04", "nip44", "nip49", "nip59"]}
once_cell = "1.2"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha256 = "1.5"
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite", "migrate", "macros", "chrono", "derive", "json" ] }
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["trace", "util", "cors"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }