# ABOUTME: GitHub Actions CI/CD workflow for Keycast testing
# ABOUTME: Runs tests on every push and pull request with proper environment setup

name: Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy, rustfmt
    
    - name: Setup test environment
      run: |
        chmod +x scripts/setup-test-env.sh
        ./scripts/setup-test-env.sh
    
    - name: Run tests
      run: cargo test --workspace --verbose
    
    - name: Run clippy
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings
    
    - name: Check formatting
      run: cargo fmt --all -- --check
    
    - name: Build release
      run: cargo build --release --workspace

  # Test with Google Cloud KMS integration (optional)
  test-gcp:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: openvine-co
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Setup test environment
      run: |
        chmod +x scripts/setup-test-env.sh
        ./scripts/setup-test-env.sh
    
    - name: Run GCP KMS tests
      env:
        USE_GCP_KMS: true
        GCP_PROJECT_ID: openvine-co
        GCP_KMS_LOCATION: global
        GCP_KMS_KEY_RING: keycast-keys
        GCP_KMS_KEY_NAME: master-key
      run: |
        # Only run GCP-specific tests
        cargo test --workspace gcp_key_manager --verbose